import re
import urllib.parse

raw_input = """10Zin -[https://www.10zin.ca/](https://www.10zin.ca/)
60fps -[https://60fps.design/](https://60fps.design/)
A1 Gallery -[https://www.a1.gallery/](https://www.a1.gallery/)
abtest.design -[https://abtest.design/](https://abtest.design/)
ace.me -[https://ace.me/](https://ace.me/)
Aceternity UI -[https://ui.aceternity.com/](https://ui.aceternity.com/)
adfolio.design -[https://www.adfolio.design/](https://www.adfolio.design/)
affinity.studio -[https://www.affinity.studio/](https://www.affinity.studio/)
Agent Builder UI -[https://agent-builder-ui-one.vercel.app/#/agents/product-discovery](https://agent-builder-ui-one.vercel.app/#/agents/product-discovery)
agentation.com -[https://www.agentation.com/](https://www.agentation.com/)
aidemos.meta.com -[https://aidemos.meta.com/](https://aidemos.meta.com/)
algora.io -[https://algora.io/](https://algora.io/)
Amicro -[https://amicro.vercel.app/](https://amicro.vercel.app/)
Angelolibero -[https://angelolibero.github.io/surface-field/](https://angelolibero.github.io/surface-field/)
Animate UI -[https://animate-ui.com/](https://animate-ui.com/)
Animos -[https://animos.app/editor](https://animos.app/editor)
animstats.com -[https://www.animstats.com/](https://www.animstats.com/)
annot.io -[https://www.annot.io/](https://www.annot.io/)
anything.com -[https://www.anything.com/](https://www.anything.com/)
app.butter.video -[https://app.butter.video/](https://app.butter.video/)
app.reve.com -[https://app.reve.com/](https://app.reve.com/)
Apple - design skill -[https://www.ui-skills.com/skills/emilkowalski/apple-design](https://www.ui-skills.com/skills/emilkowalski/apple-design)
apple-summary-slides.vercel.app -[https://apple-summary-slides.vercel.app/all](https://apple-summary-slides.vercel.app/all)
apps.apple.com -[https://apps.apple.com/us/app/command-x/id6448461551](https://apps.apple.com/us/app/command-x/id6448461551)
appshots.design -[https://appshots.design/](https://appshots.design/)
around.co -[https://www.around.co/](https://www.around.co/)
ASCII Magic -[https://www.ascii-magic.com/](https://www.ascii-magic.com/)
asciinator.app -[https://asciinator.app/](https://asciinator.app/)
Atla Design -[https://www.atla.design/](https://www.atla.design/)
atoms.dev -[https://atoms.dev/](https://atoms.dev/)
audiocleaner.ai -[https://audiocleaner.ai/remove-vocals-from-song](https://audiocleaner.ai/remove-vocals-from-song)
autodraw.com -[https://www.autodraw.com/](https://www.autodraw.com/)
awwwards.com -[https://www.awwwards.com](https://www.awwwards.com)
backblaze.com -[https://www.backblaze.com/](https://www.backblaze.com/)
baked.supply -[https://www.baked.supply/](https://www.baked.supply/)
base44.com -[https://base44.com/](https://base44.com/)
Be UI -[https://beui.dev/](https://beui.dev/)
beanheads.robertbroersma.com -[https://beanheads.robertbroersma.com/](https://beanheads.robertbroersma.com/)
beforesunset.ai -[https://www.beforesunset.ai/](https://www.beforesunset.ai/)
behance.net -[https://www.behance.net](https://www.behance.net)
Bencho -[https://bencho.dev/](https://bencho.dev/)
bentogrids.com -[https://bentogrids.com/](https://bentogrids.com/)
Best design sonx -[https://bestdesignsonx.com/](https://bestdesignsonx.com/)
Best Website Template -[https://bestwebsitetemplate.com/templates/shopify/couture](https://bestwebsitetemplate.com/templates/shopify/couture)
Best Website Templates -[https://bestwebsitetemplate.com/templates/framer/origo-studio](https://bestwebsitetemplate.com/templates/framer/origo-studio)
bezier.method.ac -[https://bezier.method.ac/](https://bezier.method.ac/)
billiondollarpitchdecks.com -[https://www.billiondollarpitchdecks.com/](https://www.billiondollarpitchdecks.com/)
bio.link -[https://bio.link/](https://bio.link/)
blip.net -[https://blip.net/](https://blip.net/)
blipbillboards.com -[https://www.blipbillboards.com/](https://www.blipbillboards.com/)
blitzit.app -[https://www.blitzit.app/](https://www.blitzit.app/)
bmrk.cc -[https://bmrk.cc/](https://bmrk.cc/)
Book of Shapes -[https://bookofshapes.com/](https://bookofshapes.com/)
bookmarkify.io -[https://www.bookmarkify.io/](https://www.bookmarkify.io/)
boomvideo.app -[https://www.boomvideo.app/](https://www.boomvideo.app/)
brandingwebsite.com -[https://www.brandingwebsite.com/](https://www.brandingwebsite.com/)
bravemark.co -[https://www.bravemark.co/](https://www.bravemark.co/)
brutalistwebsites.com -[https://brutalistwebsites.com/](https://brutalistwebsites.com/)
Bryant -[https://bestwebsitetemplate.com/templates/webflow/bryant](https://bestwebsitetemplate.com/templates/webflow/bryant)
bryntaylor.co.uk -[https://www.bryntaylor.co.uk/platform/framer](https://www.bryntaylor.co.uk/platform/framer)
bugsplat.com -[https://www.bugsplat.com/](https://www.bugsplat.com/)
builtformars.com -[https://builtformars.com/](https://builtformars.com/)
Bund UI -[https://bundui.io/](https://bundui.io/)
businessideasdb.com -[https://businessideasdb.com/](https://businessideasdb.com/)
bynapkin.com -[https://bynapkin.com/guides/reddit](https://bynapkin.com/guides/reddit)
calltoidea.com -[https://www.calltoidea.com](https://www.calltoidea.com)
calltoinspiration.com -[https://calltoinspiration.com/](https://calltoinspiration.com/)
Campagano -[https://www.campagano.com/work/rainier](https://www.campagano.com/work/rainier)
canarymail.io -[https://canarymail.io/](https://canarymail.io/)
capacity.so -[https://capacity.so/](https://capacity.so/)
captioneer.com -[https://www.captioneer.com/](https://www.captioneer.com/)
cara.app -[https://cara.app/](https://cara.app/)
carbonmade.com -[https://carbonmade.com/](https://carbonmade.com/)
celtx.com -[https://www.celtx.com/](https://www.celtx.com/)
Central Sonatype -[https://central.sonatype.com/artifact/io.github.valentinerutto/orbmotion](https://central.sonatype.com/artifact/io.github.valentinerutto/orbmotion)
charts.supply -[https://charts.supply/](https://charts.supply/)
chatbase.co -[https://www.chatbase.co/](https://www.chatbase.co/)
chorus.com -[https://chorus.com/](https://chorus.com/)
chromewebstore.google.com -[https://chromewebstore.google.com/detail/button-stealer/iiikidmnimlpahbeknmkeonmemajpccj](https://chromewebstore.google.com/detail/button-stealer/iiikidmnimlpahbeknmkeonmemajpccj)
Clain stone - CBirds -[https://github.com/clainstone/cbirds](https://github.com/clainstone/cbirds)
clickpilot.app -[https://clickpilot.app/](https://clickpilot.app/)
cofolios.com -[https://www.cofolios.com/](https://www.cofolios.com/)
collectui.com -[https://collectui.com](https://collectui.com)
commercecream.com -[https://commercecream.com/](https://commercecream.com/)
compresto.app -[https://compresto.app/](https://compresto.app/)
conversion.ai -[https://conversion.ai/](https://conversion.ai/)
convert-compress.com -[https://convert-compress.com/](https://convert-compress.com/)
Cooldock -[https://cooldock.app/](https://cooldock.app/)
coolshap.es -[https://coolshap.es/](https://coolshap.es/)
corgi.insure -[https://www.corgi.insure/](https://www.corgi.insure/)
cosmos.so -[https://www.cosmos.so](https://www.cosmos.so)
Craft UI -[https://www.craftui.space/loaders?slug=group--solar](https://www.craftui.space/loaders?slug=group--solar)
crayo.ai -[https://crayo.ai/](https://crayo.ai/)
creativefuel.ai -[https://creativefuel.ai/](https://creativefuel.ai/)
CSS Design Awards -[https://www.cssdesignawards.com/sites/the-ride/50163/](https://www.cssdesignawards.com/sites/the-ride/50163/)
cssdesignawards.com -[https://www.cssdesignawards.com](https://www.cssdesignawards.com)
csspro.com -[https://csspro.com/](https://csspro.com/)
CTA Gallery -[https://www.cta.gallery/](https://www.cta.gallery/)
cudekai.com -[https://www.cudekai.com/](https://www.cudekai.com/)
Cult UI -[https://www.cult-ui.com/](https://www.cult-ui.com/)
curated.supply -[https://www.curated.supply/](https://www.curated.supply/)
curationofcurations.com -[https://www.curationofcurations.com/](https://www.curationofcurations.com/)
Cutting mat bg generator -[https://cutting-mat-generator.vercel.app/](https://cutting-mat-generator.vercel.app/)
cyfe.com -[https://www.cyfe.com/](https://www.cyfe.com/)
dark.design -[https://dark.design](https://dark.design)
darkmodedesign.com -[https://www.darkmodedesign.com](https://www.darkmodedesign.com)
deadlinkchecker.com -[https://www.deadlinkchecker.com/](https://www.deadlinkchecker.com/)
deadsimplesites.com -[https://deadsimplesites.com/](https://deadsimplesites.com/)
Deck Gallery -[https://www.deck.gallery/wetransfer-ideas-report-2020/](https://www.deck.gallery/wetransfer-ideas-report-2020/)
deck.gallery -[https://www.deck.gallery/](https://www.deck.gallery/)
deckd.io -[https://www.deckd.io/](https://www.deckd.io/)
delights.design -[https://delights.design/](https://delights.design/)
delphi.tools -[https://delphi.tools/](https://delphi.tools/)
Design Minis -[https://www.designminis.com/](https://www.designminis.com/)
design.com -[https://www.design.com/](https://www.design.com/)
Designeer XYZ -[https://designeer.xyz/](https://designeer.xyz/)
designspells.com -[https://designspells.com/](https://designspells.com/)
designsphere.xyz -[https://www.designsphere.xyz/](https://www.designsphere.xyz/)
Destory - Spirtefusion -[https://destroy.spritefusion.com/](https://destroy.spritefusion.com/)
detail.design -[https://detail.design/](https://detail.design/)
dictionaries.io -[https://dictionaries.io/](https://dictionaries.io/)
displaybuddy.app -[https://displaybuddy.app/](https://displaybuddy.app/)
Dither Garden -[https://www.dithergarden.com/](https://www.dithergarden.com/)
Dither Me This -[https://doodad.dev/dither-me-this/](https://doodad.dev/dither-me-this/)
Docent js -[https://docentjs.dev/](https://docentjs.dev/)
donotpay.com -[https://donotpay.com/](https://donotpay.com/)
Dot Forge -[https://dotforge.vercel.app/](https://dotforge.vercel.app/)
dotts.se -[https://dotts.se/](https://dotts.se/)
dribbble.com -[https://dribbble.com](https://dribbble.com)
dub.co -[https://dub.co/](https://dub.co/)
durves.com -[https://www.durves.com/](https://www.durves.com/)
eagle.cool -[https://www.eagle.cool/](https://www.eagle.cool/)
endel.io -[https://endel.io/](https://endel.io/)
epiceasing.com -[https://epiceasing.com/](https://epiceasing.com/)
essaytone.com -[https://www.essaytone.com/en](https://www.essaytone.com/en)
etoro.com -[https://www.etoro.com/](https://www.etoro.com/)
Eve - mocks -[https://eve-mocks.vercel.app/](https://eve-mocks.vercel.app/)
evendeals.com -[https://www.evendeals.com/](https://www.evendeals.com/)
Evil charts -[https://evilcharts.com/](https://evilcharts.com/)
fabric.so -[https://fabric.so/](https://fabric.so/)
FAQ Block -[https://design.intentui.com/blocks/marketing/faq/08](https://design.intentui.com/blocks/marketing/faq/08)
finaldraft.com -[https://www.finaldraft.com/](https://www.finaldraft.com/)
finderhub.app -[https://www.finderhub.app/](https://www.finderhub.app/)
flora.ai -[https://flora.ai/](https://flora.ai/)
fluidmotion.app -[https://fluidmotion.app/](https://fluidmotion.app/)
fontsinuse.com -[https://fontsinuse.com](https://fontsinuse.com)
footer.design -[https://www.footer.design](https://www.footer.design)
Forge UI -[https://forgeui.in/](https://forgeui.in/)
fotocaja.com -[https://fotocaja.com/](https://fotocaja.com/)
foureditors.com -[https://www.foureditors.com/collections/all-our-bundles](https://www.foureditors.com/collections/all-our-bundles)
frameauth.com -[https://frameauth.com/](https://frameauth.com/)
framercrafts.com -[https://framercrafts.com/](https://framercrafts.com/)
frameroverrides.com -[https://frameroverrides.com/](https://frameroverrides.com/)
frameshare.social -[https://frameshare.social/](https://frameshare.social/)
framestack.co -[https://framestack.co/](https://framestack.co/)
framify.design -[https://framify.design/](https://framify.design/)
freelancethings.co -[https://www.freelancethings.co/](https://www.freelancethings.co/)
Frontend - Design skills Anthropic -[https://www.ui-skills.com/skills/anthropics/frontend-design](https://www.ui-skills.com/skills/anthropics/frontend-design)
fronty.com -[https://fronty.com/](https://fronty.com/)
gallereee.com -[https://www.gallereee.com/](https://www.gallereee.com/)
Game UI -[https://takayustudio.jp/](https://takayustudio.jp/)
gatheros.co -[https://www.gatheros.co/](https://www.gatheros.co/)
gempix2ai.ai -[https://gempix2ai.ai/](https://gempix2ai.ai/)
Generative Charts -[https://generativecharts.com/](https://generativecharts.com/)
Get Droppy -[https://getdroppy.app/](https://getdroppy.app/)
get.apollo.io -[https://get.apollo.io/toolfolio](https://get.apollo.io/toolfolio)
get.emergent.sh -[https://get.emergent.sh/3sto528d9545](https://get.emergent.sh/3sto528d9545)
get.toggl.com -[https://get.toggl.com/h9s5yw9qq7wp](https://get.toggl.com/h9s5yw9qq7wp)
GetLayers AI -[https://www.getlayers.ai/](https://www.getlayers.ai/)
godly.website -[https://godly.website](https://godly.website)
Gradient Background -[https://backgrounds.supply/gradient-lab](https://backgrounds.supply/gradient-lab)
GradienTool -[https://www.gradientool.com/](https://www.gradientool.com/)
Griflan -[https://griflan.com/](https://griflan.com/)
gtmetrix.com -[https://gtmetrix.com/](https://gtmetrix.com/)
h1gallery.com -[https://h1gallery.com/](https://h1gallery.com/)
Halftone Maker -[https://halftonemaker.com/](https://halftonemaker.com/)
handyarrows.com -[https://handyarrows.com/](https://handyarrows.com/)
headers.club -[https://headers.club/](https://headers.club/)
headshot-generator.ai -[https://headshot-generator.ai/christmas](https://headshot-generator.ai/christmas)
higgsfield.ai -[https://higgsfield.ai/](https://higgsfield.ai/)
highlights.design -[https://www.highlights.design/](https://www.highlights.design/)
holygrid.studio -[https://holygrid.studio/](https://holygrid.studio/)
httpster.net -[https://httpster.net](https://httpster.net)
hyperframer.com -[https://www.hyperframer.com/](https://www.hyperframer.com/)
hyvector.com -[https://www.hyvector.com/](https://www.hyvector.com/)
Icon Museum -[https://icon.museum/](https://icon.museum/)
IDE Extension - Shadcn UI -[https://www.shadcnblocks.com/ide-extension](https://www.shadcnblocks.com/ide-extension)
inbound.new -[https://inbound.new/](https://inbound.new/)
inclusivecolors.com -[https://www.inclusivecolors.com/](https://www.inclusivecolors.com/)
Inspirectory -[https://inspirectory.com/](https://inspirectory.com/)
Inspora -[https://www.inspora.design/](https://www.inspora.design/)
intelbee.com -[https://intelbee.com/](https://intelbee.com/)
itsnicethat.com -[https://www.itsnicethat.com](https://www.itsnicethat.com)
jenni.ai -[https://jenni.ai/](https://jenni.ai/)
Joglo Pages -[https://joglo.pages.dev/](https://joglo.pages.dev/)
junebytes.com -[https://junebytes.com/dropnotch](https://junebytes.com/dropnotch)
KaitoSec -[https://kaitosec.app/](https://kaitosec.app/)
Kamran -[https://kamran.fyi/candle](https://kamran.fyi/candle)
Kargul -[https://kargul.studio/](https://kargul.studio/)
karis.im -[https://karis.im/](https://karis.im/)
Kernel Workshop -[https://kernelworkshop.vizuara.ai/](https://kernelworkshop.vizuara.ai/)
Keyline icons - 1178 free -[https://keylineicons.com/icons](https://keylineicons.com/icons)
kimi.com -[https://www.kimi.com/](https://www.kimi.com/)
Kinetics -[https://kinetics.colorion.co/](https://kinetics.colorion.co/)
kintsu.ai -[https://kintsu.ai/](https://kintsu.ai/)
Kobra System - React -[https://kobra.systems/components/magnetic-dropzone](https://kobra.systems/components/magnetic-dropzone)
kosmik.app -[https://www.kosmik.app/](https://www.kosmik.app/)
lab.coreviz.io -[https://lab.coreviz.io/not-available](https://lab.coreviz.io/not-available)
labs.google -[https://labs.google/fx/tools/flow](https://labs.google/fx/tools/flow)
labs.google.com -[https://labs.google.com/pomelli/about/](https://labs.google.com/pomelli/about/)
Land Book -[https://land-book.com](https://land-book.com)
landify.design -[https://landify.design/](https://landify.design/)
landingfolio.com -[https://www.landingfolio.com](https://www.landingfolio.com)
landings.dev -[https://landings.dev/](https://landings.dev/)
Lapa Ninja -[https://www.lapa.ninja](https://www.lapa.ninja)
Lapa Ninja -[https://www.siteinspire.com](https://www.siteinspire.com)
lastpass.com -[https://www.lastpass.com/](https://www.lastpass.com/)
layouts.dev -[https://layouts.dev/](https://layouts.dev/)
learnplace.ai -[https://learnplace.ai/](https://learnplace.ai/)
letsenhance.io -[https://letsenhance.io/](https://letsenhance.io/)
Light Rails -[https://light-stroke-rail.vercel.app/](https://light-stroke-rail.vercel.app/)
liinks.co -[https://www.liinks.co/](https://www.liinks.co/)
limora.ai -[https://limora.ai/](https://limora.ai/)
linklyhq.com -[https://linklyhq.com/](https://linklyhq.com/)
lium.ai -[https://www.lium.ai/](https://www.lium.ai/)
lo.cafe -[https://lo.cafe/notchnook](https://lo.cafe/notchnook)
Loadmo -[https://loadmo.re/](https://loadmo.re/)
Local Mode UI -[https://localmode.ai/](https://localmode.ai/)
Logggos -[https://www.logggos.club/](https://www.logggos.club/)
Logoinspo -[https://logoinspo.com/](https://logoinspo.com/)
logome.ai -[https://logome.ai/](https://logome.ai/)
logosystem.co -[https://logosystem.co/](https://logosystem.co/)
Louisnguynen -[https://louisnguyen.co/startup](https://louisnguyen.co/startup)
maced.ai -[https://www.maced.ai/](https://www.maced.ai/)
macfolio.com -[https://macfolio.com](https://macfolio.com)
Magic UI -[https://magicui.design/](https://magicui.design/)
magicpath.ai -[https://magicpath.ai/](https://magicpath.ai/)
Mapcn -[https://www.mapcn.dev/](https://www.mapcn.dev/)
Marinoe to world -[https://marionietoworld.com/](https://marionietoworld.com/)
marqly.com -[https://www.marqly.com/](https://www.marqly.com/)
matte.app -[https://matte.app/](https://matte.app/)
maxibestof.one -[https://www.maxibestof.one](https://www.maxibestof.one)
meetsponsors.com -[https://meetsponsors.com/](https://meetsponsors.com/)
memelord.com -[https://www.memelord.com/](https://www.memelord.com/)
Metal Forge XYZ -[https://metalforge.xyz/](https://metalforge.xyz/)
Microkit -[https://microkit.co/](https://microkit.co/)
Minifolio -[https://www.minifolio.in/](https://www.minifolio.in/)
Minimal Gallery -[https://minimal.gallery/](https://minimal.gallery/)
misterhorse.com -[https://misterhorse.com/](https://misterhorse.com/)
Mobbin -[https://mobbin.com](https://mobbin.com)
modyfi.com -[https://modyfi.com/](https://modyfi.com/)
mossaik.app -[https://mossaik.app/](https://mossaik.app/)
Motion Primitives -[https://motion-primitives.com/](https://motion-primitives.com/)
motion.zajno.com -[https://motion.zajno.com/](https://motion.zajno.com/)
Motioon -[https://mtioon.com/](https://mtioon.com/)
Movements dev -[https://www.movements.dev/](https://www.movements.dev/)
Movulab -[https://movulab.fun/](https://movulab.fun/)
mult.dev -[https://mult.dev/](https://mult.dev/)
multiplayer.app -[https://www.multiplayer.app/](https://www.multiplayer.app/)
muz.li -[https://muz.li/](https://muz.li/)
mymind.com -[https://mymind.com/](https://mymind.com/)
Nalysnyk Framer -[https://vasya-nalysnyk.framer.website/](https://vasya-nalysnyk.framer.website/)
nanobanana2ai.ai -[https://nanobanana2ai.ai/](https://nanobanana2ai.ai/)
nanobanapro.com -[https://nanobanapro.com/](https://nanobanapro.com/)
nanophoto.ai -[https://nanophoto.ai/](https://nanophoto.ai/)
nav.supply -[https://nav.supply/](https://nav.supply/)
Navbar Gallery -[https://www.navbar.gallery/](https://www.navbar.gallery/)
nexlev.io -[https://www.nexlev.io/](https://www.nexlev.io/)
nexus-ui.dev -[https://nexus-ui.dev/](https://nexus-ui.dev/)
nicelydone.club -[https://nicelydone.club](https://nicelydone.club)
nordpass.com -[https://nordpass.com/](https://nordpass.com/)
Notion Agents -[https://apps.apple.com/us/app/notion-agents/id6759811964](https://apps.apple.com/us/app/notion-agents/id6759811964)
octarine.app -[https://octarine.app/](https://octarine.app/)
octolens.com -[https://octolens.com/](https://octolens.com/)
of10.com -[https://1of10.com/](https://1of10.com/)
Ogimage CN -[https://www.ogimagecn.com/](https://www.ogimagecn.com/)
ogimage.gallery -[https://www.ogimage.gallery/](https://www.ogimage.gallery/)
Oguz Design -[https://oguz.design/](https://oguz.design/)
ohdear.app -[https://ohdear.app/](https://ohdear.app/)
onepagelove.com -[https://onepagelove.com](https://onepagelove.com)
onetapapp.co -[https://www.onetapapp.co/](https://www.onetapapp.co/)
oriorai.com -[https://www.oriorai.com/](https://www.oriorai.com/)
oss.gallery -[https://oss.gallery/](https://oss.gallery/)
Ossium -[https://ossium.in/](https://ossium.in/)
Overflow -[https://www.overflow.design/isometric/](https://www.overflow.design/isometric/)
overrrides.com -[https://overrrides.com/](https://overrrides.com/)
pageai.pro -[https://pageai.pro/](https://pageai.pro/)
pageflows.com -[https://pageflows.com](https://pageflows.com)
pagesection.com -[https://www.pagesection.com/editor](https://www.pagesection.com/editor)
pagespeed.web.dev -[https://pagespeed.web.dev/](https://pagespeed.web.dev/)
paper.design -[https://paper.design/](https://paper.design/)
paperanimator.com -[https://paperanimator.com/](https://paperanimator.com/)
partnerstack.lusha.com -[https://partnerstack.lusha.com/ex2zjrck6xsv-dr6kr7](https://partnerstack.lusha.com/ex2zjrck6xsv-dr6kr7)
pdf0.dev -[https://pdf0.dev/](https://pdf0.dev/)
pebblely.com -[https://pebblely.com/](https://pebblely.com/)
Pick a Pattern -[https://tabbied.com/patterns/](https://tabbied.com/patterns/)
pics.io -[https://pics.io/](https://pics.io/)
pikzels.com -[https://pikzels.com/](https://pikzels.com/)
pixelsnap.com -[https://pixelsnap.com/](https://pixelsnap.com/)
Pointilliser -[https://pointilliser.elwyn.co/](https://pointilliser.elwyn.co/)
pop.site -[https://pop.site/](https://pop.site/)
Portfolio Inspiration -[https://perfolios.shwn.design/](https://perfolios.shwn.design/)
Posts design -[https://posts.design/](https://posts.design/)
prism.openai.com -[https://prism.openai.com/](https://prism.openai.com/)
Pro beui dev -[https://pro.beui.dev/](https://pro.beui.dev/)
Pro d2 Studio -[https://pro.d2studio.dev/icons](https://pro.d2studio.dev/icons)
propal.io -[https://www.propal.io/](https://www.propal.io/)
pttrns.com -[https://pttrns.com](https://pttrns.com)
purevpn.com -[https://www.purevpn.com/order-now.php](https://www.purevpn.com/order-now.php)
pushkeen.ai -[https://pushkeen.ai/](https://pushkeen.ai/)
quiver.ai -[https://quiver.ai/](https://quiver.ai/)
Railway -[https://railway.com/free-vm](https://railway.com/free-vm)
Ramp Design -[https://ramp.design/](https://ramp.design/)
randoma11y.com -[https://randoma11y.com/](https://randoma11y.com/)
rankhog.com -[https://rankhog.com/](https://rankhog.com/)
rasa.com -[https://rasa.com/](https://rasa.com/)
React Bits -[https://reactbits.dev/](https://reactbits.dev/)
reallygoodemails.com -[https://reallygoodemails.com/](https://reallygoodemails.com/)
receiptmaker.ai -[https://receiptmaker.ai/](https://receiptmaker.ai/)
recent.design -[http://recent.design/](http://recent.design/)
Reelfolio -[https://reelfolio.io/](https://reelfolio.io/)
refero.design -[https://refero.design](https://refero.design)
refflow.com -[https://www.refflow.com](https://www.refflow.com)
remixlab.framer.wiki -[https://remixlab.framer.wiki/](https://remixlab.framer.wiki/)
removesorawatermark.online -[https://www.removesorawatermark.online/sora2-video](https://www.removesorawatermark.online/sora2-video)
restream.io -[https://restream.io/](https://restream.io/)
righthand.ai -[https://www.righthand.ai/](https://www.righthand.ai/)
rocketlawyer.com -[https://www.rocketlawyer.com/](https://www.rocketlawyer.com/)
roles.at -[https://roles.at/](https://roles.at/)
roomxai.com -[https://roomxai.com/](https://roomxai.com/)
rss.app -[https://rss.app/](https://rss.app/)
s.design -[https://www.404s.design/](https://www.404s.design/)
saasemails.xyz -[https://www.saasemails.xyz/](https://www.saasemails.xyz/)
saaslandingpage.com -[https://saaslandingpage.com](https://saaslandingpage.com)
saaspo.com -[https://www.saaspo.com](https://www.saaspo.com)
same.energy -[https://same.energy/search](https://same.energy/search)
Save Design -[https://save.design/explore?tab=elements](https://save.design/explore?tab=elements)
Save Design -[https://save.design/explore](https://save.design/explore)
save.day -[https://www.save.day/](https://www.save.day/)
savee.com -[https://savee.com/](https://savee.com/)
sayfone.com -[https://www.sayfone.com/](https://www.sayfone.com/)
scade.pro -[https://scade.pro/](https://scade.pro/)
science.nasa.gov -[https://science.nasa.gov/specials/your-name-in-landsat/](https://science.nasa.gov/specials/your-name-in-landsat/)
screenlane.com -[https://screenlane.com](https://screenlane.com)
screensdesign.com -[https://screensdesign.com/](https://screensdesign.com/)
scribbbles.design -[https://www.scribbbles.design/](https://www.scribbbles.design/)
scrnshts.club -[https://scrnshts.club](https://scrnshts.club)
Search System -[https://searchsystem.co/](https://searchsystem.co/)
seesaw.website -[https://www.seesaw.website/](https://www.seesaw.website/)
semplice.com -[https://www.semplice.com/](https://www.semplice.com/)
Seomade -[https://seomade.app/](https://seomade.app/)
seomatic.ai -[https://seomatic.ai/](https://seomatic.ai/)
serif.sh -[https://www.serif.sh/](https://www.serif.sh/)
Shad CN UI -[https://www.shadcnblocks.com/admin-dashboard](https://www.shadcnblocks.com/admin-dashboard)
Shadcn App Shell -[https://reui.io/blocks/application/app-shell](https://reui.io/blocks/application/app-shell)
Shadcn Registry Directory -[https://shoogle.dev/directory](https://shoogle.dev/directory)
ShadCN UI -[https://ui.shadcn.com/](https://ui.shadcn.com/)
shapeoholic.live -[https://shapeoholic.live/](https://shapeoholic.live/)
shapes.gallery -[https://www.shapes.gallery/](https://www.shapes.gallery/)
shapes.tools -[https://www.shapes.tools/](https://www.shapes.tools/)
sher.sh -[https://sher.sh/](https://sher.sh/)
shieldcn.dev -[https://shieldcn.dev/](https://shieldcn.dev/)
shipfa.st -[https://shipfa.st/](https://shipfa.st/)
shortcat.app -[https://shortcat.app/](https://shortcat.app/)
showcase.supply -[https://www.showcase.supply/](https://www.showcase.supply/)
shrink.media -[https://www.shrink.media/](https://www.shrink.media/)
siteliner.com -[https://www.siteliner.com/](https://www.siteliner.com/)
sizey.app -[https://sizey.app/](https://sizey.app/)
sketchto.com -[https://www.sketchto.com/](https://www.sketchto.com/)
Skipper UI -[https://skiper-ui.com/](https://skiper-ui.com/)
slack.com -[https://slack.com/](https://slack.com/)
slapmac.com -[https://slapmac.com/](https://slapmac.com/)
slicetube.io -[https://www.slicetube.io/](https://www.slicetube.io/)
slidy.app -[https://slidy.app/](https://slidy.app/)
sneakpeekit.com -[https://sneakpeekit.com/](https://sneakpeekit.com/)
socialproofexamples.com -[https://socialproofexamples.com/](https://socialproofexamples.com/)
sora2video.com -[https://sora2video.com/](https://sora2video.com/)
sotion.so -[https://sotion.so/](https://sotion.so/)
Space Type Generator -[https://spacetypegenerator.com/](https://spacetypegenerator.com/)
sparktoro.com -[https://sparktoro.com/](https://sparktoro.com/)
Spherium -[https://tryspherium.com/](https://tryspherium.com/)
spottedinprod.com -[https://www.spottedinprod.com/](https://www.spottedinprod.com/)
spotterstudio.com -[https://www.spotterstudio.com/](https://www.spotterstudio.com/)
squoosh.app -[https://squoosh.app/](https://squoosh.app/)
st dev -[https://21st.dev/](https://21st.dev/)
steep.design -[https://www.steep.design/](https://www.steep.design/)
stippling.app -[https://stippling.app/](https://stippling.app/)
String Tune -[https://string-tune.fiddle.digital/](https://string-tune.fiddle.digital/)
subscribr.ai -[https://subscribr.ai/](https://subscribr.ai/)
supahero.io -[https://supahero.io/](https://supahero.io/)
superclick.app -[https://superclick.app/](https://superclick.app/)
Supply Made By Oversight -[https://supply.madebyoversight.com/](https://supply.madebyoversight.com/)
svg.designcode.io -[https://svg.designcode.io/](https://svg.designcode.io/)
svgexport.io -[https://svgexport.io/](https://svgexport.io/)
Swift UX App -[https://www.swiftux.app/uicomponents/membership-card-paywall](https://www.swiftux.app/uicomponents/membership-card-paywall)
swisstransfer.com -[https://www.swisstransfer.com/en](https://www.swisstransfer.com/en)
t3.chat -[https://t3.chat/chat](https://t3.chat/chat)
tabsurfer.com -[https://tabsurfer.com/](https://tabsurfer.com/)
Tailark -[https://tailark.com/](https://tailark.com/)
Tasteful Interfaces -[https://kombai.com/selects/](https://kombai.com/selects/)
tecca.io -[https://tecca.io/](https://tecca.io/)
Tester army -[https://tester.army/e2e](https://tester.army/e2e)
testimonial.to -[https://testimonial.to/](https://testimonial.to/)
texts.com -[https://texts.com/](https://texts.com/)
textsniper.app -[https://textsniper.app/](https://textsniper.app/)
thegistof.me -[https://thegistof.me/](https://thegistof.me/)
thenty.io -[https://thenty.io/](https://thenty.io/)
thumbnailcreator.com -[https://www.thumbnailcreator.com/](https://www.thumbnailcreator.com/)
thumbnailpilot.com -[https://thumbnailpilot.com/](https://thumbnailpilot.com/)
thumbsup.tv -[https://thumbsup.tv/](https://thumbsup.tv/)
tiimoapp.com -[https://www.tiimoapp.com/](https://www.tiimoapp.com/)
timgabe.com -[https://timgabe.com/](https://timgabe.com/)
tinypng.com -[https://tinypng.com/](https://tinypng.com/)
tinystartups.com -[https://www.tinystartups.com/](https://www.tinystartups.com/)
tinyvid.io -[https://tinyvid.io/](https://tinyvid.io/)
tinywow.com -[https://tinywow.com/](https://tinywow.com/)
topnotch.app -[https://topnotch.app/](https://topnotch.app/)
transitions.dev -[https://transitions.dev/](https://transitions.dev/)
try.krispcall.com -[https://try.krispcall.com/m3biphfl8hds](https://try.krispcall.com/m3biphfl8hds)
try.monday.com -[https://try.monday.com/8lod746m1pg5-pm](https://try.monday.com/8lod746m1pg5-pm)
try.quillbot.com -[https://try.quillbot.com/toolfolio](https://try.quillbot.com/toolfolio)
try.soona.co -[https://try.soona.co/gsyor4hiysrf](https://try.soona.co/gsyor4hiysrf)
try.webcatalog.io -[https://try.webcatalog.io/zf5r4dkci6mn](https://try.webcatalog.io/zf5r4dkci6mn)
trybloom.ai -[https://www.trybloom.ai/](https://www.trybloom.ai/)
tryprofound.com -[https://www.tryprofound.com/](https://www.tryprofound.com/)
tubebuddy.com -[https://www.tubebuddy.com/](https://www.tubebuddy.com/)
tubelab.net -[https://tubelab.net/](https://tubelab.net/)
typotab.com -[https://www.typotab.com/](https://www.typotab.com/)
UI Arc -[https://uiarc.dev/](https://uiarc.dev/)
UI Verse -[https://uiverse.io/](https://uiverse.io/)
uigarage.net -[https://uigarage.net](https://uigarage.net)
uilogos.co -[https://uilogos.co/](https://uilogos.co/)
uisources.com -[https://www.uisources.com](https://www.uisources.com)
Umanmade -[https://www.umanmade.com/](https://www.umanmade.com/)
unclutterapp.com -[https://unclutterapp.com/](https://unclutterapp.com/)
uncovr.app -[https://uncovr.app/](https://uncovr.app/)
Unique Transition -[https://unique-transition-between-grid-and.vercel.app/](https://unique-transition-between-grid-and.vercel.app/)
unsection.com -[https://www.unsection.com/](https://www.unsection.com/)
Urbanly -[https://urbanly.org/](https://urbanly.org/)
usekinet.app -[https://usekinet.app/](https://usekinet.app/)
uselima.com -[https://uselima.com/](https://uselima.com/)
variant.com -[https://variant.com/](https://variant.com/)
Vector Halftone Maker -[https://halftone.xoihazard.com/](https://halftone.xoihazard.com/)
vibecodeapp.com -[https://www.vibecodeapp.com/](https://www.vibecodeapp.com/)
vidclue.com -[https://vidclue.com/](https://vidclue.com/)
videotok.app -[https://www.videotok.app/](https://www.videotok.app/)
vidflux.ai -[https://vidflux.ai/](https://vidflux.ai/)
visualgpt.io -[https://visualgpt.io/](https://visualgpt.io/)
visualjournal.it -[https://visualjournal.it/](https://visualjournal.it/)
vivaldi.com -[https://vivaldi.com/](https://vivaldi.com/)
vscodethemes.com -[https://vscodethemes.com/](https://vscodethemes.com/)
wellows.com -[https://wellows.com/](https://wellows.com/)
wetransfer.com -[https://wetransfer.com/](https://wetransfer.com/)
Wies law soltes -[https://wieslawsoltes.github.io/PdfSpace/](https://wieslawsoltes.github.io/PdfSpace/)
wonder.design -[https://wonder.design/](https://wonder.design/)
wonderlist.design -[https://www.wonderlist.design/](https://www.wonderlist.design/)
wozcode.com -[https://www.wozcode.com/](https://www.wozcode.com/)
zen-browser.app -[https://zen-browser.app](https://zen-browser.app)
Zoah -[https://zoah.com/]"""

lines = [l.strip() for l in raw_input.strip().splitlines() if l.strip()]
print(f"Total input lines: {len(lines)}")

# Parse items
items = []
for l in lines:
    m = re.match(r'^(.*?)\s*-\s*\[(.*?)\](?:\((.*?)\))?', l)
    if m:
        name = m.group(1).strip()
        url = (m.group(3) or m.group(2)).strip()
        items.append((name, url))
    else:
        print("Failed to parse:", l)

print(f"Parsed items: {len(items)}")

# Normalizing names where required per rule 7 & 8:
name_cleanups = {
    "Destory - Spirtefusion": "Destroy — Spritefusion",
    "Docent js": "Docent.js",
    "Clain stone - CBirds": "Clain Stone — CBirds",
    "Cutting mat bg generator": "Cutting Mat Background Generator",
    "Wies law soltes": "Wieslaw Soltes — PdfSpace",
    "Louisnguynen": "Louis Nguyen — Startup",
    "Marinoe to world": "Marinoe to World",
    "Best design sonx": "Best Design Sonx",
    "Movements dev": "Movements.dev",
    "Kobra System - React": "Kobra System — React Magnetic Dropzone",
    "IDE Extension - Shadcn UI": "IDE Extension — shadcn/ui",
    "Shad CN UI": "shadcn/ui — Admin Dashboard",
    "ShadCN UI": "shadcn/ui",
    "Shadcn App Shell": "shadcn App Shell",
    "Shadcn Registry Directory": "shadcn Registry Directory",
    "Swift UX App": "Swift UX App — Membership Card Paywall",
    "Campagano": "Campagano — Rainier",
    "Deck Gallery": "Deck Gallery — WeTransfer Ideas Report 2020",
    "Kamran": "Kamran — Candle",
    "Tester army": "Tester Army — E2E",
    "Pro d2 Studio": "Pro D2 Studio — Icons",
    "Central Sonatype": "Central Sonatype — ORB Motion",
    "Railway": "Railway — Free VM",
    "Best Website Templates": "Best Website Templates — Origo Studio",
    "Best Website Template": "Best Website Template — Couture",
    "Angelolibero": "Angelolibero — Surface Field",
    "CSS Design Awards": "CSS Design Awards — The Ride",
    "Apple - design skill": "Apple Design Skill",
    "Frontend - Design skills Anthropic": "Frontend — Anthropic Design Skill",
    "Eve - mocks": "Eve Mocks",
    "st dev": "21st.dev",
    "Keyline icons - 1178 free": "Keyline Icons — 1178 Free Icons"
}

# Fix the mislabeled Lapa Ninja -> siteInspire
# Check:
# Lapa Ninja - https://www.siteinspire.com -> siteInspire
cleaned_items = []
for name, url in items:
    clean_name = name_cleanups.get(name, name)
    if "siteinspire.com" in url:
        clean_name = "siteInspire"
    cleaned_items.append((clean_name, url))

# Check duplicates by canonical URL
def canonical_url(u):
    p = urllib.parse.urlparse(u)
    host = p.netloc.lower()
    if host.startswith('www.'):
        host = host[4:]
    path = p.path.rstrip('/')
    return host + path

seen_urls = {}
deduped_items = []
duplicates_found = []

for name, url in cleaned_items:
    c_url = canonical_url(url)
    if c_url in seen_urls:
        duplicates_found.append((name, url, seen_urls[c_url]))
    else:
        seen_urls[c_url] = (name, url)
        deduped_items.append((name, url))

print(f"\nDuplicates found in input: {len(duplicates_found)}")
for d in duplicates_found:
    print("  Duplicate:", d)

print(f"Unique resources after deduplication: {len(deduped_items)}")

# Sort alphabetically by resource name (case-insensitive)
deduped_items.sort(key=lambda x: x[0].lower())

# Build the markdown content
md_lines = [
    "# UI/UX & Frontend Resource Directory",
    "",
    "A curated collection of UI/UX, frontend development, web design, animation, developer tools, inspiration, AI tools, and creative resources.",
    "",
    f"> **Total Curated Resources:** {len(deduped_items)} unique tools and platforms.",
    ">",
    "> **Format:** Standard normalized markdown links sorted alphabetically by resource name.",
    "",
    "## Resource Directory",
    ""
]

current_letter = ""
for idx, (name, url) in enumerate(deduped_items, 1):
    first_char = name[0].upper()
    if not first_char.isalpha():
        first_char = "#"
    
    # Optional group headings by letter
    if first_char != current_letter:
        current_letter = first_char
        md_lines.append(f"### {current_letter}")
        md_lines.append("")

    # Format: 1. Resource Name — [https://example.com/](https://example.com/)
    md_lines.append(f"{idx}. {name} — [{url}]({url})")

md_content = "\n".join(md_lines) + "\n"

with open(r"c:\Users\91970\Downloads\mahi-ui-verse\resources\website-directory.md", "w", encoding="utf-8") as f:
    f.write(md_content)

print("Successfully written website-directory.md")
